# Generated by Django 4.2.7 on 2023-11-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
    ]
